# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-18 17:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190118_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcar',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
