# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-07 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180907_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^09\\d{2}-?\\d{3}-?\\d{3}$', 'Please enter valid Taiwanese phone number.')]),
        ),
    ]
